[package]
name = "harp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
anyhow = "1.0"
home = "0.5"
strum = { version = "0.24", features = ["derive"] }
